server:
  port: 8078
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SpringTest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: wac62461818
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.example.demo.Model          # 所有实体类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

